// <auto-generated />
namespace Concessionaria.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _12345 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_12345));
        
        string IMigrationMetadata.Id
        {
            get { return "201611100254453_12345"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
